<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Isabella’s Assignments</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Isabella's Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="R-Basics.html">R Basics</a>
</li>
<li>
  <a href="Assignments.html">Assignments</a>
</li>
<li>
  <a href="Exam-1.html">Exam 1</a>
</li>
<li>
  <a href="Exam-2.html">Exam 2</a>
</li>
<li>
  <a href="Links.html">Links</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Isabella’s Assignments</h1>

</div>


<p>CRIM 250: Statistics for the Social Sciences</p>
<div id="assignment-1" class="section level1">
<h1>Assignment 1</h1>
<p><strong>Collaborators: Isabella Werneck. </strong></p>
<p>Due date: September 20th</p>
<div id="problem-1" class="section level3">
<h3>Problem 1</h3>
<p>Install the datasets package on the console below using <code>install.packages("datasets")</code>. Now load the library.</p>
<pre class="r"><code>dat &lt;- USArrests</code></pre>
<p>Load the USArrests dataset and rename it <code>dat</code>. Note that this dataset comes with R, in the package datasets, so there’s no need to load data from your computer. Why is it useful to rename the dataset?</p>
<p>Answer: It is useful to rename the dataset to avoid disturbing the original data. It also makes it easier to locate the dataset you are currently looking at.</p>
</div>
<div id="problem-2" class="section level3">
<h3>Problem 2</h3>
<p>Use this command to make the state names into a new variable called State.</p>
<pre class="r"><code>dat$state &lt;- tolower(rownames(USArrests))</code></pre>
<p>This dataset has the state names as row names, so we just want to make them into a new variable. We also make them all lower case, because that will help us draw a map later - the map function requires the states to be lower case.</p>
<p>List the variables contained in the dataset <code>USArrests</code>.</p>
<pre class="r"><code>names(dat)</code></pre>
<pre><code>## [1] &quot;Murder&quot;   &quot;Assault&quot;  &quot;UrbanPop&quot; &quot;Rape&quot;     &quot;state&quot;</code></pre>
<p>Answer: The variables contained in USArrests are: Murder, Assault, Rape, and UrbanPop (number of people from urban areas).</p>
</div>
<div id="problem-3" class="section level3">
<h3>Problem 3</h3>
<p>What type of variable (from the DVB chapter) is <code>Murder</code>?</p>
<p>Answer: <code>Murder</code> is a categorical variable, since it is a form of categorizing groups of people, and it is non-numerical.</p>
<p>What R Type of variable is it?</p>
<p>Answer: In R, <code>Murder</code> is a character variable.</p>
</div>
<div id="problem-4" class="section level3">
<h3>Problem 4</h3>
<p>What information is contained in this dataset, in general? What do the numbers mean?</p>
<p>Answer: The USArrests dataset shows the rate of arrests per 100,000 residents in different US states in 1973. It divides the arrests by the crime: Murder, Assault, and Rape. The dataset also includes the number of people living in urban areas.</p>
</div>
<div id="problem-5" class="section level3">
<h3>Problem 5</h3>
<p>Draw a histogram of <code>Murder</code> with proper labels and title.</p>
<pre class="r"><code>hist(USArrests$Murder, main = &quot;Arrest for Murder in the US in 1973&quot;, xlab = &quot;Murder Arrests per 100,000 people&quot;, ylab = &quot;Frequency of US States&quot;)</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="problem-6" class="section level3">
<h3>Problem 6</h3>
<p>Please summarize <code>Murder</code> quantitatively. What are its mean and median? What is the difference between mean and median? What is a quartile, and why do you think R gives you the 1st Qu. and 3rd Qu.?</p>
<pre class="r"><code>summary(USArrests$Murder)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.800   4.075   7.250   7.788  11.250  17.400</code></pre>
<p>As shown above, the mean of the data set is 7.788 and the median is 7.250. The difference between the mean and the median is that mean is the average number of arrests, while the median is the middle point of the dataset. This means that half of the dataset is under 7.250, and the other half is over 7.250. A quartile divides a dataset in four parts, each containing 25% of the data. The interquartile range (IQR) contains the middle 50% of the data, and it is determined by the upper bound of the 1st Qu. and the lower bound of the 3rd Qu. The 2nd Qu, which marks the middle of the IQR, is the dataset’s median point. R gives us the 1st Qu. and 3rd Qu. because the IQR is important for determining how skewed the distribution of the dataset is in relation to the median It is also useful in giving you an overview of where the values lie.</p>
</div>
<div id="problem-7" class="section level3">
<h3>Problem 7</h3>
<p>Repeat the same steps you followed for <code>Murder</code>, for the variables <code>Assault</code> and <code>Rape</code>. Now plot all three histograms together. You can do this by using the command <code>par(mfrow=c(3,1))</code> and then plotting each of the three.</p>
<pre class="r"><code>#Histogram for assault arrests

hist(USArrests$Assault, main = &quot;Arrest for Assault in the US in 1973&quot;, xlab = &quot;Assault Arrests per 100,000 people&quot;, ylab = &quot;Frequency of US States&quot;)</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-7-1.png" width="480" /></p>
<pre class="r"><code>#Histogram for rape arrests

hist(USArrests$Rape, main = &quot;Arrest for Rape in the US in 1973&quot;, xlab = &quot;Rape Arrests per 100,000 people&quot;, ylab = &quot;Frequency of US States&quot;)</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-7-2.png" width="480" /></p>
<pre class="r"><code>#Histograms for `Murder`, `Assault`, and `Rape`

par(mfrow=c(3,1))
hist(USArrests$Murder, main = &quot;Arrest for Murder in the US in 1973&quot;, xlab = &quot;Murder Arrests per 100,000 people&quot;, ylab = &quot;Frequency of US States&quot;)
hist(USArrests$Assault, main = &quot;Arrest for Assault in the US in 1973&quot;, xlab = &quot;Assault Arrests per 100,000 people&quot;, ylab = &quot;Frequency of US States&quot;)
hist(USArrests$Rape, main = &quot;Arrest for Rape in the US in 1973&quot;, xlab = &quot;Rape Arrests per 100,000 people&quot;, ylab = &quot;Frequency of US States&quot;)</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-7-3.png" width="480" /></p>
<p>What does the command par do, in your own words (you can look this up by asking R <code>?par</code>)?</p>
<p>Answer: The command par is used to set graphical parameters.</p>
<p>What can you learn from plotting the histograms together?</p>
<p>Answer: Plotting histograms together is good for comparing results, specifically in comparing how skewed each graph is. You can tell from the graph, for example, that while the <code>rape</code> and <code>murder</code> graphs are more right-skewed, the <code>assault</code> graph is more skewed towards the right.</p>
</div>
<div id="problem-8" class="section level3">
<h3>Problem 8</h3>
<p>In the console below (not in text), type <code>install.packages("maps")</code> and press Enter, and then type <code>install.packages("ggplot2")</code> and press Enter. This will install the packages so you can load the libraries.</p>
<p>Run this code:</p>
<pre class="r"><code># install.packages(&quot;maps&quot;)
# install.packages(&quot;ggplot2&quot;)

library(&#39;maps&#39;) 
library(&#39;ggplot2&#39;) 

ggplot(dat, aes(map_id=state, fill=Murder)) + 
  geom_map(map=map_data(&quot;state&quot;)) + 
  expand_limits(x=map_data(&quot;state&quot;)$long, y=map_data(&quot;state&quot;)$lat)</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-9-1.png" width="720" /></p>
<p>What does this code do? Explain what each line is doing.</p>
<p>Answer: This code creates a map of US States and their arrest rates for murder in 1973. The first line (<code>ggplot...</code>) establishes the variables: US States and murder rates. It also says that the color fill of the map will represent murder rates. The second line identifies the dataset for the map, and the third establishes the dimensions for the map.</p>
<p><span class="math display">\[\\[2in]\]</span></p>
</div>
</div>
<div id="assignment-2" class="section level1">
<h1>Assignment 2</h1>
<div id="problem-1-1" class="section level3">
<h3>Problem 1</h3>
<pre class="r"><code>#setwd(&quot;/Users/isabellawerneck/Desktop/RStudio Data/Assignment 2&quot;)

dat &lt;- read.csv(file = &#39;dat.nsduh.small.1.csv&#39;)</code></pre>
<p>What are the dimensions of the dataset?</p>
<pre class="r"><code>dim(dat)</code></pre>
<pre><code>## [1] 171   7</code></pre>
<pre class="r"><code>#View(dat)</code></pre>
<p>Answer: There are 7 columns and 171 rows. In other words, 7 variables and 171 respondents.</p>
</div>
<div id="problem-2-1" class="section level3">
<h3>Problem 2</h3>
<pre class="r"><code>names(dat)</code></pre>
<pre><code>## [1] &quot;mjage&quot;     &quot;cigage&quot;    &quot;iralcage&quot;  &quot;age2&quot;      &quot;sexatract&quot; &quot;speakengl&quot;
## [7] &quot;irsex&quot;</code></pre>
<p>Describe the variables in the dataset.</p>
<p>Answer: - Age when first used marijuana/hashish (<code>mjage</code>): continuous quantitative variable - Age when first started using cigarettes everyday (<code>cigage</code>): continuous quantitative variable - Age when first used alcohol (<code>iralcage</code>): continuous quantitative variable - Age of respondents organized in categories (<code>age2</code>): categorical ordinal variable - Gender of respondents (<code>irsex</code>): categorical nominal variable - Sexual attraction organized in categories (<code>sexatract</code>): categorical nominal variable - How well the respondents speak English (<code>speakengl</code>): categorical ordinal variable</p>
<p>What is this dataset about? Who collected the data, what kind of sample is it, and what was the purpose of generating the data?</p>
<p>Answer: The dataset is about 171 individuals living in the Unites States and the age they began using marijuana, alcohol, and cigarettes. The data also includes the individuals’ age, gender, sexual orientation, and whether they speak English. The data was collected in 2019 by the National Survey of Drug Use and Health, a nation-wide study sponsored by the Substance Abuse and Mental Health Services Administration. The dataset includes only a small sample of the survey.</p>
<p>The purpose of generating this data is to create a dataset representative of the US population. This kind of information is useful for addressing social and health problems in the United States, such as drug addiction.</p>
</div>
<div id="problem-3-age-and-gender" class="section level3">
<h3>Problem 3: Age and Gender</h3>
<p>What is the age distribution of the sample like? Make sure you read the codebook to know what the variable values mean.</p>
<pre class="r"><code>hist(dat$age2, main=&quot;Age Distribution in 2019 NSDUH Survey&quot;, xlab=&quot;Age Category&quot;, ylab = &quot;Frequency&quot;)</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Answer: The dataset presents the individuals’ ages through categories that encompass an age range. The ages range from 12 to 65 years old or older, categorized from 1 to 17. The most common ages, as seen above, belong to category 15, which includes ages between 35 and 49 years old.</p>
<p>Do you think this age distribution representative of the US population? Why or why not?</p>
<p>Answer: According to “Statista”, the age distribution of the US in 2020 is the following: 18.37% are ages 0-14, 65% are ages 15 to 64, and 16.63% are 65 and older. The age distribution in the data set is consistent with this information, since the graph is left-skewed and the most frequent ages lie between categories 12 and 16. Another website, “KFF”, shows that the biggest demographic in the US in 2019 was ages 35-45, which is also consistent with the dataset. It is important to note that since the study only considers individuals aged 12 or older, it cannot fully represent the age distribution in the US.</p>
<p>Is the sample balanced in terms of gender? If not, are there more females or males?</p>
<pre class="r"><code>table(dat$irsex)</code></pre>
<pre><code>## 
##  1  2 
## 91 80</code></pre>
<p>Answer: 1 represents males and 2 represents females. There are 11 more males than females, but the sample remains relatively balanced in terms of gender.</p>
<p>Use this code to draw a stacked bar plot to view the relationship between sex and age. What can you conclude from this plot?</p>
<pre class="r"><code>tab.agesex &lt;- table(dat$irsex, dat$age2)
barplot(tab.agesex,
        main = &quot;Stacked barchart&quot;,
        xlab = &quot;Age category&quot;, ylab = &quot;Frequency&quot;,
        legend.text = rownames(tab.agesex),
        beside = FALSE) # Stacked bars (default))</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-15-1.png" width="672" /> Answer: I can conclude that most of the age categories are equal in gender, including categories 4, 10, 11, 12, 13, and 15. However, two of the younger categories (6 and 7) had more males, as well as the last two categories (16 and 17). These differences do not seem to form a pattern.</p>
</div>
<div id="problem-4-1" class="section level3">
<h3>Problem 4</h3>
<p>For which of the three substances included in the dataset (marijuana, alcohol, and cigarettes) do individuals tend to use the substance earlier?</p>
<pre class="r"><code>#Summary of age when first used marijuana/hashish
summary(dat$mjage)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    7.00   14.00   16.00   15.99   17.50   35.00</code></pre>
<pre class="r"><code>#Summary of alcohol age of first use
summary(dat$iralcage)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    5.00   13.00   15.00   14.95   17.00   23.00</code></pre>
<pre class="r"><code>#Summary of age when first started smoking cigarettes everyday
summary(dat$cigage)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   10.00   15.00   17.00   17.65   19.00   50.00</code></pre>
<p>Answer: According to the summary of the dataset, individuals tend to use alcohol earlier than cigarettes or marijuana/hashish. The mean of first-time use age for alcohol is 14.95, while the mean ages for marijuana/hashish and cigarettes are 15.99 and 17.65 respectively. The minimum, median, and max of the three are also consistent with this - alcohol has the lowest ages for all of them. This suggests that individuals tend to start using alcohol earlier than cigarettes or marijuana/hashish.</p>
</div>
<div id="problem-5-sexual-orientation" class="section level3">
<h3>Problem 5: Sexual orientation</h3>
<p>What does the distribution of sexual attraction look like? Is this what you expected?</p>
<pre class="r"><code>counts &lt;- table(dat$sexatract)
barplot(counts, main=&quot;Sexual Orientation of Individuals in NSDUH 2019 Survey&quot;, xlab=&quot;Sexual Orientation Categories&quot;, ylab = &quot;Frequency&quot;)</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>The Sexual Orientation categories are as follows: 1: I am only attracted to the opposite sex 2: I am mostly attracted to the opposite sex 3: I am equally attracted to males and females 4: I am mostly attracted to the same sex 5: I am only attracted to the same sex 6: I am not sure 99: Legitimate skip</p>
<p>Answer: The distribution of sexual orientation is highly skewed to the right. The first category, which represents heterosexual individuals, has the highest frequency. It represents the vast majority of participants of this survey. I would say this is close to what I imagined. Most individuals today are heterosexuals, even though the number of members of the LGBTQ+ community is increasing over the years. It is also important to note that an individual’s answer to this question might not be truthful; homophobia is still very common and present in the United States, and that might discourage individuals from answering to the survey truthfully, even if the survey is anonymous. However, even if all participants told the truth about their sexual orientation, I believe that the number of heterosexuals would still be predominant in the data.</p>
<p>What is the distribution of sexual attraction by gender?</p>
<pre class="r"><code>counts &lt;- table(dat$irsex, dat$sexatract)
barplot(counts, main= &quot;Sexual Orientation vs Gender of Individuals in 2019 NSDUH Survey &quot;, xlab=&quot;Sexual Orientation Categories&quot;, ylab= &quot;Frequency&quot;)</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Answer: The majority of heterosexuals are male, while there is a female predominance in categories 2 and 3, which represent individuals who are, to some extent, attracted to the opposite sex. Category 4 is split evenly between males and females and there is a male predominance in categories 5 and 6. More males also refrained from stating their sexual orientation.</p>
</div>
<div id="problem-6-english-speaking" class="section level3">
<h3>Problem 6: English Speaking</h3>
<p>What does the distribution of English speaking look like in the sample? Is this what you might expect for a random sample of the US population?</p>
<pre class="r"><code>counts &lt;- table(dat$speakengl)
barplot(counts, main=&quot;Self-Evaluation of English Fluency of Individuals in NSDUH 2019 Survey&quot;, xlab=&quot;English Fluency Categories&quot;, ylab = &quot;Frequency&quot;)</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Answer: The grand majority of the participants responded “1”, which means they speak English very well. Categories 2 and 3, which correspond to speaking English well and not well, have significantly less people. This is what I would expect from a random sample of the US population since there are many immigrants living in the country, some of which don’t speak fluent English.</p>
<p>Are there more English speaker females or males?</p>
<pre class="r"><code>counts &lt;- table(dat$irsex, dat$speakengl)
barplot(counts, main= &quot;Gender vs English Fluency of Individuals in 2019 NSDUH Survey &quot;, xlab=&quot;English Fluency Categories&quot;, ylab= &quot;Frequency&quot;)</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>Answer: There seems to be an equal number of males and females in category 1, which represents individuals who speak English very well. There are significantly more males in category 2, which represents individuals who speak English well. Lastly, category 3, which represents individuals who don’t speak English well, has significantly more females. Though there is an equal number of males and females in category 1, category 2 has more males and category 3 only has females. Therefore, there are more males who speak “good” English than females. However, it is important to keep in mind that these results come from self-evaluation rather than English-fluency tests, making the categories completely arbitrary. They might provide an inaccurate representation of the US population.</p>
<p>Works Cited: <a href="https://www.kff.org/other/state-indicator/distribution-by-age/?currentTimeframe=0&amp;sortModel=%7B%22colId%22:%22Location%22,%22sort%22:%22asc%22%7D" class="uri">https://www.kff.org/other/state-indicator/distribution-by-age/?currentTimeframe=0&amp;sortModel=%7B%22colId%22:%22Location%22,%22sort%22:%22asc%22%7D</a> <a href="https://www.statista.com/statistics/270000/age-distribution-in-the-united-states/" class="uri">https://www.statista.com/statistics/270000/age-distribution-in-the-united-states/</a></p>
</div>
</div>
<div id="assignment-3" class="section level1">
<h1>Assignment 3</h1>
<p><strong>Collaborators: </strong> Niko Amber</p>
<p>The dataset used is from a textbook by Brian S. Everitt about crime in the US in 1960. The data originate from the Uniform Crime Report of the FBI and other government sources. The data for 47 states of the USA are given.</p>
<p>Dataset codebook:</p>
<p>R: Crime rate: # of offenses reported to police per million population</p>
<p>Age: The number of males of age 14-24 per 1000 population</p>
<p>S: Indicator variable for Southern states (0 = No, 1 = Yes)</p>
<p>Ed: Mean of years of schooling x 10 for persons of age 25 or older</p>
<p>Ex0: 1960 per capita expenditure on police by state and local government</p>
<p>Ex1: 1959 per capita expenditure on police by state and local government</p>
<p>LF: Labor force participation rate per 1000 civilian urban males age 14-24</p>
<p>M: The number of males per 1000 females</p>
<p>N: State population size in hundred thousands</p>
<p>NW: The number of non-whites per 1000 population</p>
<p>U1: Unemployment rate of urban males per 1000 of age 14-24</p>
<p>U2: Unemployment rate of urban males per 1000 of age 35-39</p>
<p>W: Median value of transferable goods and assets or family income in tens of $</p>
<p>X: The number of families per 1000 earning below 1/2 the median income</p>
<p>We are interested in checking whether the reported crime rate (# of offenses reported to police per million population) and the average education (mean number of years of schooling for persons of age 25 or older) are related.</p>
<div id="problem-1-2" class="section level3">
<h3>Problem 1</h3>
<div id="how-many-observations-are-there-in-the-dataset-to-what-does-each-observation-correspond" class="section level4">
<h4>How many observations are there in the dataset? To what does each observation correspond?</h4>
<pre class="r"><code>library(readr)
library(knitr)
dat.crime &lt;- read_delim(&quot;crime_simple.txt&quot;, delim = &quot;\t&quot;)</code></pre>
<pre><code>## Rows: 47 Columns: 14</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;\t&quot;
## dbl (14): R, Age, S, Ed, Ex0, Ex1, LF, M, N, NW, U1, U2, W, X</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p><strong>Answer: There are 47 observations. Each observation corresponds to an American state.</strong></p>
</div>
</div>
<div id="problem-2-2" class="section level3">
<h3>Problem 2</h3>
<div id="draw-a-scatterplot-of-the-two-variables.-calculate-the-correlation-between-the-two-variables.-can-you-come-up-with-an-explanation-for-this-relationship" class="section level4">
<h4>Draw a scatterplot of the two variables. Calculate the correlation between the two variables. Can you come up with an explanation for this relationship?</h4>
<pre class="r"><code>plot(dat.crime$Ed, dat.crime$R, main = &quot;Relationship between reported crime rate and average education in American states&quot;, xlab = &quot;Mean years of schooling times 10&quot;, ylab = &quot;Offences reported to police per million population&quot;, cex.main=0.8, cex.lab=0.8, col=&quot;blue&quot;)</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<pre class="r"><code>cor(dat.crime$Ed, dat.crime$R)</code></pre>
<pre><code>## [1] 0.3228349</code></pre>
<p><strong>Answer: There is a low positive correlation between the variables since the number is lower than 0.95 and a positive number. Though it is difficult to draw conclusions on this scatterplot from solely these results, I would guess that it means that more educated people are more likely to report a crime.</strong></p>
</div>
</div>
<div id="problem-3-1" class="section level3">
<h3>Problem 3</h3>
<div id="regress-reported-crime-rate-y-on-average-education-x-and-call-this-linear-model-crime.lm-and-write-the-summary-of-the-regression-by-using-this-code-which-makes-it-look-a-little-nicer-r-evalfalse-kablesummarycrime.lmcoef-digits-2." class="section level4">
<h4>Regress reported crime rate (y) on average education (x) and call this linear model <code>crime.lm</code> and write the summary of the regression by using this code, which makes it look a little nicer <code>{r, eval=FALSE} kable(summary(crime.lm)$coef, digits = 2)</code>.</h4>
<pre class="r"><code>crime.lm &lt;- lm(formula = dat.crime$R ~ dat.crime$Ed, data = (dat.crime))

kable(summary(crime.lm)$coef, digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Estimate</th>
<th align="right">Std. Error</th>
<th align="right">t value</th>
<th align="right">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-27.40</td>
<td align="right">51.81</td>
<td align="right">-0.53</td>
<td align="right">0.60</td>
</tr>
<tr class="even">
<td align="left">dat.crime$Ed</td>
<td align="right">1.12</td>
<td align="right">0.49</td>
<td align="right">2.29</td>
<td align="right">0.03</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="problem-4-2" class="section level3">
<h3>Problem 4</h3>
<div id="are-the-four-assumptions-of-linear-regression-satisfied-to-answer-this-draw-the-relevant-plots.-write-a-maximum-of-one-sentence-per-assumption." class="section level4">
<h4>Are the four assumptions of linear regression satisfied? To answer this, draw the relevant plots. (Write a maximum of one sentence per assumption.)</h4>
<p><strong>1. Linearity assumption</strong></p>
<pre class="r"><code>plot(dat.crime$Ed, crime.lm$residuals, ylim = c(-15, 15), main = &quot;Residuals vs. X&quot;, ylab = &quot;Residuals&quot;, xlab = &quot;X, Mean years of schooling times 10&quot;, col=&quot;red&quot;)
abline(h=0, lty=&quot;dashed&quot;)</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p><strong>Answer: The linearity assumption is satisfied because there is no pattern in the scatterplot of the residuals vs X, so the scatterplot of X and Y is linear.</strong></p>
<p><strong>2. Independence assumption</strong></p>
<pre class="r"><code>plot(dat.crime$Ed, crime.lm$residuals, ylim = c(-15, 15), main = &quot;Residuals vs. X&quot;, ylab = &quot;Residuals&quot;, xlab = &quot;X, Mean years of schooling times 10&quot;, col=&quot;red&quot;)
abline(h=0, lty=&quot;dashed&quot;)</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p><strong>Answer: The independence assumption is satisfied since there are no irregularities or clumps in the scatterplot above, which means that the errors are independent from each other.</strong></p>
<p><strong>3. Equal variance assumption</strong></p>
<pre class="r"><code>plot(crime.lm, which = 3)</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p><strong>Answer: The scale-location scatterplot does not show significant trends, which means that the residuals have constant variance and the assumption is satisfied.</strong></p>
<p><strong>4. Normal population assumption</strong></p>
<pre class="r"><code>plot(crime.lm, which = 2, col=&quot;blue&quot;)</code></pre>
<p><img src="Assignment-3_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p><strong>Answer: The scatterplot is light-tailed, which means that it is not evenly distributed.</strong></p>
</div>
</div>
<div id="problem-5-1" class="section level3">
<h3>Problem 5</h3>
<div id="is-the-relationship-between-reported-crime-and-average-education-statistically-significant-report-the-estimated-coefficient-of-the-slope-the-standard-error-and-the-p-value.-what-does-it-mean-for-the-relationship-to-be-statistically-significant" class="section level4">
<h4>Is the relationship between reported crime and average education statistically significant? Report the estimated coefficient of the slope, the standard error, and the p-value. What does it mean for the relationship to be statistically significant?</h4>
<pre class="r"><code>#dat.crime.c = scale(dat.crime, center = TRUE, scale = FALSE) #scaling the data

summary(crime.lm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = dat.crime$R ~ dat.crime$Ed, data = (dat.crime))
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -60.061 -27.125  -4.654  17.133  91.646 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)  -27.3967    51.8104  -0.529   0.5996  
## dat.crime$Ed   1.1161     0.4878   2.288   0.0269 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 37.01 on 45 degrees of freedom
## Multiple R-squared:  0.1042, Adjusted R-squared:  0.08432 
## F-statistic: 5.236 on 1 and 45 DF,  p-value: 0.02688</code></pre>
<p><strong>Answer: The relationship is statistically significant since there are no asterisks for the intercept and only one for the slope. The estimated coefficient of the slope is 1.1161, the standard error is 37.01, and the p-value is 0.02688. The small p-value means we should reject the null hypothesis because it shows that there is a significant relationship between reported crime and average education.</strong></p>
</div>
</div>
<div id="problem-6-1" class="section level3">
<h3>Problem 6</h3>
<div id="how-are-reported-crime-and-average-education-related-in-other-words-for-every-unit-increase-in-average-education-how-does-reported-crime-rate-change-per-million-per-state" class="section level4">
<h4>How are reported crime and average education related? In other words, for every unit increase in average education, how does reported crime rate change (per million) per state?</h4>
<p><strong>Answer: For every unit increase in average education, crime rate (per million) changes by 1.1161.</strong></p>
</div>
</div>
<div id="problem-7-1" class="section level3">
<h3>Problem 7</h3>
<div id="can-you-conclude-that-if-individuals-were-to-receive-more-education-then-crime-will-be-reported-more-often-why-or-why-not" class="section level4">
<h4>Can you conclude that if individuals were to receive more education, then crime will be reported more often? Why or why not?</h4>
<p><strong>Answer: It is a possibility that by increasing education, crime would be reported more often. The results of the data show that there is a positive correlation between the two variables, and a linear regression model works to demonstrate this relationship. However, correlation does not necessarily mean causality. There could be other factors involved in this trend that we are not aware of that are causing the correlation that we are seeing. So, in order to reach this conclusion, we should look at the other variables in the dataset, like per capita expenditure on police by state and local government, labor force participation rates, and the number of non-whites per 1000 people. All of these could have an effect on crime reports.</strong></p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
