<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Isabella Werneck" />

<meta name="date" content="2021-11-01" />

<title>Exam 2</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Isabella's Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="R-Basics.html">R Basics</a>
</li>
<li>
  <a href="Assignments.html">Assignments</a>
</li>
<li>
  <a href="Exam-1.html">Exam 1</a>
</li>
<li>
  <a href="Exam-2.html">Exam 2</a>
</li>
<li>
  <a href="Links.html">Links</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Exam 2</h1>
<h4 class="author">Isabella Werneck</h4>
<h4 class="date">11/01/2021</h4>

</div>


<div id="instructions" class="section level1">
<h1>Instructions</h1>
<ol style="list-style-type: lower-alpha">
<li><p>Create a folder in your computer (a good place would be under Crim 250, Exams).</p></li>
<li><p>Download the dataset from the Canvas website (sim.data.csv) onto that folder, and save your Exam 2.Rmd file in the same folder.</p></li>
<li><p>Data description: This dataset provides (simulated) data about 200 police departments in one year. It contains information about the funding received by the department as well as incidents of police brutality. Suppose this dataset (sim.data.csv) was collected by researchers to answer this question: <strong>“Does having more funding in a police department lead to fewer incidents of police brutality?”</strong></p></li>
<li><p>Codebook:</p></li>
</ol>
<ul>
<li>funds: How much funding the police department received in that year in millions of dollars.</li>
<li>po.brut: How many incidents of police brutality were reported by the department that year.</li>
<li>po.dept.code: Police department code</li>
</ul>
</div>
<div id="problem-1-eda-10-points" class="section level1">
<h1>Problem 1: EDA (10 points)</h1>
<p>Describe the dataset and variables. Perform exploratory data analysis for the two variables of interest: funds and po.brut.</p>
<pre class="r"><code>dat &lt;- read.csv(file = &#39;sim.data.csv&#39;)

plot(dat$funds, dat$po.brut, main = &quot;Police Department Funding vs Incidents of Police Brutality&quot;, ylab = &quot;Incidents of police brutality reported by department that year&quot;, xlab = &quot;Police department funding received that year in millions of dollars&quot;, cex.main=1, cex.lab=0.7, col=&quot;blue&quot;)</code></pre>
<p><img src="Exam-2_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<pre class="r"><code>cor(dat$funds, dat$po.brut)</code></pre>
<pre><code>## [1] -0.9854706</code></pre>
<p><strong>There are 200 obersvations and three variables in the dataset. The three variables include “funds,” which represents how much funding the police department received in that year (in millions of dollars), “po.brut,” which represents how many incidents of police brutality were reported by the department that year, and “po.depart.code,” which represents the police department code. The two variables of interest, “funds” and “po.brut”, show strong negative correlation to each other according to the scatterplot above. The correlation coefficient -0.9854706 confirms this visual analysis.</strong></p>
</div>
<div id="problem-2-linear-regression-30-points" class="section level1">
<h1>Problem 2: Linear regression (30 points)</h1>
<ol style="list-style-type: lower-alpha">
<li>Perform a simple linear regression to answer the question of interest. To do this, name your linear model “reg.output” and write the summary of the regression by using “summary(reg.output)”.</li>
</ol>
<pre class="r"><code># Remember to remove eval=FALSE!!
reg.output &lt;- lm(formula = dat$po.brut ~ dat$funds, data = (dat))

summary(reg.output)</code></pre>
<pre><code>## 
## Call:
## lm(formula = dat$po.brut ~ dat$funds, data = (dat))
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.9433 -0.2233  0.2544  0.5952  1.1803 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 40.543069   0.282503  143.51   &lt;2e-16 ***
## dat$funds   -0.367099   0.004496  -81.64   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9464 on 198 degrees of freedom
## Multiple R-squared:  0.9712, Adjusted R-squared:  0.971 
## F-statistic:  6666 on 1 and 198 DF,  p-value: &lt; 2.2e-16</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Report the estimated coefficient, standard error, and p-value of the slope. Is the relationship between funds and incidents statistically significant? Explain.</li>
</ol>
<p><strong>It has been established by the scatterplot of x vs y that there is a strong negative correlation between “funds” and “po.brut”, which means that when there is bigger funding, less police brutality incidents are reported. The slope estimated coefficient is -0.367099 with an estimated error of 0.004496, which means that there is little variance in the data. The three asterisks next to the intercept and slope show that there is a statistically significant p-value, and the small p-value (&lt;2e-16) confirms this. Based on these results, we can reject the null hypothesis, which means that there is a relationship between “funds” and “po.brut.” However, correlation does not imply causation. Though there is a strong negative correlation between the two variables, that doesn’t mean that more funding leads to fewer incidents of police brutality, only that when there is more funding, more incidents are reported by the department.</strong></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Draw a scatterplot of po.brut (y-axis) and funds (x-axis). Right below your plot command, use abline to draw the fitted regression line, like this:</li>
</ol>
<pre class="r"><code># Remember to remove eval=FALSE!!

plot(dat$funds, dat$po.brut, main = &quot;Police Department Funding vs Incidents of Police Brutality&quot;, ylab = &quot;Incidents of police brutality reported by department that year&quot;, xlab = &quot;Police department funding received that year in millions of dollars&quot;, cex.main=1, cex.lab=0.7)

abline(reg.output, col = &quot;red&quot;, lwd=2)</code></pre>
<p><img src="Exam-2_files/figure-html/unnamed-chunk-3-1.png" width="384" /> Does the line look like a good fit? Why or why not?</p>
<p><strong>The line does seem like a good fit except for in between 80 and 100 millions of dollars in funding and between 20 and 40 million. This can still be considered a good model.</strong></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Are the four assumptions of linear regression satisfied? To answer this, draw the relevant plots. (Write a maximum of one sentence per assumption.) If not, what might you try to do to improve this (if you had more time)?</li>
</ol>
<pre class="r"><code>plot(reg.output)</code></pre>
<p><img src="Exam-2_files/figure-html/unnamed-chunk-4-1.png" width="672" /><img src="Exam-2_files/figure-html/unnamed-chunk-4-2.png" width="672" /><img src="Exam-2_files/figure-html/unnamed-chunk-4-3.png" width="672" /><img src="Exam-2_files/figure-html/unnamed-chunk-4-4.png" width="672" /></p>
<pre class="r"><code>plot(dat$funds, dat$residuals, ylim = c(-20, 100), main = &quot;Residuals vs. X&quot;, ylab = &quot;Residuals&quot;, xlab = &quot;X, Police department funding that year in millions of dollars&quot;, col=&quot;red&quot;)
abline(h=0, lty=&quot;dashed&quot;)</code></pre>
<p><img src="Exam-2_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p><strong>1. Linearity assumption: The assumption is not satisfied because in the residuals vs fitted graph, the red line is far from straight, and the points are very close to the red line, which suggest that a linear model might not be the best fit for the data</strong></p>
<p><strong>2. Independence assumption: Looking at the residuals vs X, the independence assumption is not satisfied because the plots are scattered approximately along y=60, which means that the errors in the dataset might be dependent on each other.</strong></p>
<p><strong>3. Equal variance assumption: The scale-location plot shows significant trends along the red line, which suggests that the residuals don’t have equal variance and that the assumption is not satisfied.</strong></p>
<p><strong>4. Normal population assumption: The normal qq plot is left skewed and there is a light tail at the end of it, but the distribution seems almost normal, which means that the assumption is satisfied.</strong></p>
<p><strong>If I had more time, I would try transforming the y or x by adding a quadratic term or making a log transformation to see if the regression would look better. Alternatively, I’d include more variables in the dataset (like whether they use body cameras or not) that might have importance to the model, and I’d change the method of collecting data on police brutality. There is a chance that many of the results were fabricated by the police departments, so I’d try to get that information another way.</strong></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Answer the question of interest based on your analysis.</li>
</ol>
<p><strong>Though three of the assumptions were not satisfied, The R-squared value of the adjusted linear regression is 0.971, which is close to 1. Still, these results suggest that the relationship between police department funding and reported police brutality cases might not be linear. Regardless, there still seems to be a strong negative correlation between the two variables, which means that departments with bigger funding have less police brutality reports. Again, that doesn’t mean that bigger funding directly causes a department to have less police brutality cases.</strong></p>
</div>
<div id="problem-3-data-ethics-10-points" class="section level1">
<h1>Problem 3: Data ethics (10 points)</h1>
<p>Describe the dataset. Considering our lecture on data ethics, what concerns do you have about the dataset? Once you perform your analysis to answer the question of interest using this dataset, what concerns might you have about the results?</p>
<p><strong>The dataset looks at 200 police departments in the United States. It includes information on how much funding they received in a year and how many cases of police brutality were reported by them that same year. The biggest concern I have about the dataset is that the police brutality cases were reported by the police departments themselves. They have more than enough reason to fabricate their numbers if it serves their purposes. Therefore, the dataset cannot fully address the question of interest, since it cannot tell the real number of police brutality cases.</strong></p>
<p><strong>Once I performed the analysis, the main concerns I have are that a linear model might not be the best to represent the data. I also think that many variables are missing from the dataset — if we had more variables, like whether they have body cameras or not, or maybe public trust in police officers from specific departments, we might get more accurate results.</strong></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
